ALTER TABLE t_p79249079_api_url_update.users
  ADD COLUMN IF NOT EXISTS email VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS username_updated_at TIMESTAMP DEFAULT NULL;
